name: 'Resource Pack Validator'
description: 'Validate minecraft java edition resource packs'
author: David "MrKinau" Luedtke
inputs:
  resourcepack:
    description: 'Path to the resourcepack (zip or folder)'
    required: false
    default: 'resourcepack'
  config:
    description: 'Path to the Resource Pack Validator config file'
    required: false
    default: 'config.json'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/mrkinau/rpvalidator:master'
  args:
    - '-rp'
    - '${{ inputs.resourcepack}}'
    - '-config'
    - '${{ inputs.config }}'
branding:
  icon: package
  color: yellow